In [7]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
from db_util import Database

db = Database("/Users/chriswarner/TFData.db")

all_results = db.get_all_athlete_results()
relay_results = db.get_all_relay_results()

In [9]:
relay_results

,school_id,event,result,result2,place,athlete_names,school_name,team_name,school_type,meet_type,meet_num,gender,year
0,131,4 x 100 Relay,43.47,43.47,1.0,"Brady King, Kaleb Hayes, Trevion Williamson, L...",Gary West Side,,Public,Sectional,1,Boys,2023
1,149,4 x 100 Relay,43.95,43.95,2.0,"Donte Moore, Travon McCullough, Davion Terry, ...",Hammond Central,,Public,Sectional,1,Boys,2023
2,150,4 x 100 Relay,44.11,44.11,3.0,"Freddy Brown, DaVierre McNair, Montey Hill, Ta...",Hammond Morton,,Public,Sectional,1,Boys,2023
3,244,4 x 100 Relay,44.74,44.74,4.0,"Peyton Mueller, Jordan Jones, Khtab Ishtawi, A...",Munster,,Public,Sectional,1,Boys,2023
4,84,4 x 100 Relay,44.89,44.89,5.0,"Dandre Brown, Juan Price, Derion Morris, Jalma...",East Chicago Central,,Public,Sectional,1,Boys,2023
...,...,...,...,...,...,...,...,...,...,...,...,...,...
5476,327,4 x 800 Relay,9:48.02,588.02,23.0,"Elise Bulaoro, Emily Shepherd, Isabella Soens,...",South Bend Adams,,Public,State,1,Girls,2024
5477,182,4 x 800 Relay,9:48.21,588.21,24.0,"Alexis Byrd, Monica Lorey, Molly Isaacs, Ella ...",Jasper,,Public,State,1,Girls,2024
5478,23,4 x 800 Relay,9:50.66,590.66,25.0,"Hayden McGuire, Katie Kent, Evie Peterson, Ell...",Bloomington North,,Public,State,1,Girls,2024
5479,110,4 x 800 Relay,9:53.45,593.45,26.0,"Emma Campbell, Lindsey Fisher, Lucy Jenks, Gin...",Floyd Central,,Public,State,1,Girls,2024
5480,270,4 x 800 Relay,10:29.67,629.67,27.0,"Hannah Harrison, Reagin White, Aubrey Miller, ...",Northview,,Public,State,1,Girls,2024

In [11]:
all_events = ['Discus', 'Pole Vault', 'Shot Put', 'Long Jump', '800 Meters', '4 x 800 Relay', '4 x 400 Relay', '4 x 100 Relay', '300 Hurdles', '110 Hurdles', '100 Hurdles', '3200 Meters', '1600 Meters', '400 Meters', '200 Meters', 'High Jump']


regional_results = all_results[(all_results['meet_type'] == 'Regional')]
#display(regional_results)

regional_relay_results = relay_results[relay_results['meet_type'] == 'Regional']
#regional_relay_results

In [13]:
#EXCLUDES RELAY RESULTS, empty df's for the 3 relays

year = 2023 #FOR A SPECIFIED YEAR; CHANGE THIS VALUE TO CHANGE THE YEAR
field_events = ['Discus', 'Pole Vault', 'Shot Put', 'Long Jump', 'High Jump']
track_events = ['800 Meters', '300 Hurdles', '110 Hurdles', '100 Hurdles', '3200 Meters', '1600 Meters', '400 Meters', '200 Meters']
relay_events = ['4 x 100 Relay', '4 x 400 Relay', '4 x 800 Relay']

fieldNonQualifiers = pd.DataFrame()
trackNonQualifiers = pd.DataFrame()
relayNonQualifiers = pd.DataFrame()

regionalQualifiers = pd.DataFrame()

for meetNumber in range (1, 9): #loops through each region 
    region_results = regional_results[(regional_results['meet_num'] == meetNumber) & (regional_results['year'] == year) & (all_results['result_type'] == 'Final')] #specifies regional meet and the year, gets FINAL results only
    region_relay_results = regional_relay_results[(regional_relay_results['meet_num'] == meetNumber) & (regional_relay_results['year'] == year)]
    
    
    for event in all_events: #loops through each event of the regional meet
        region_event_results = region_results[region_results['event'] == event] #results of specific event in specific regional meet
        male_event_results = region_event_results[region_event_results['gender'] == 'Boys'].sort_values(by=['result2'], ascending=True) #divides by gender
        female_event_results = region_event_results[region_event_results['gender'] == 'Girls'].sort_values(by=['result2'], ascending=True)
        
        region_relay_event_results = region_relay_results[region_relay_results['event'] == event]
        male_relay_event_results = region_relay_event_results[region_relay_event_results['gender'] == 'Boys'].sort_values(by=['result2'], ascending=True)
        female_relay_event_results = region_relay_event_results[region_relay_event_results['gender'] == 'Girls'].sort_values(by=['result2'], ascending=True)
        
        top3Males = pd.DataFrame()
        top3Females = pd.DataFrame()
        
        top3RelayMales = pd.DataFrame()
        top3RelayFemales = pd.DataFrame()
        
        #display(male_event_results)
        #display(female_event_results)
        if (event in field_events and len(male_event_results) != 0): #top individual performers, accounts for ties
            top3Males = male_event_results.tail(3)
                
            i = -4
            while (male_event_results.iloc[-3]['result2'] == male_event_results.iloc[i]['result2']): #accounts for ties for 3rd place
                top3Males = pd.concat([top3Males, male_event_results.iloc[[i]]], ignore_index=True)
                i-=1
                    
            male_event_results = male_event_results.drop(male_event_results.index[-len(top3Males):]) #clears male_event_results of qualifiers
            fieldNonQualifiers = pd.concat([fieldNonQualifiers, male_event_results], ignore_index=True)
            
        if (event in track_events and len(male_event_results) != 0):
            top3Males = male_event_results.head(3)
                
            i = 3
            while (male_event_results.iloc[2]['result2'] == male_event_results.iloc[i]['result2']): #accounts for ties for 3rd place
                top3Males = pd.concat([top3Males, male_event_results.iloc[[i]]], ignore_index=True)
                i+=1
                
            male_event_results = male_event_results.drop(male_event_results.index[:len(top3Males)]) #clears male_event_results of qualifiers
            trackNonQualifiers = pd.concat([trackNonQualifiers, male_event_results], ignore_index=True)
            
        regionalQualifiers = pd.concat([regionalQualifiers, top3Males], ignore_index=True)
            
        if (event in field_events and len(female_event_results) != 0): #top individual performers, accounts for ties
            top3Females = female_event_results.tail(3)
            
            i = -4
            while (female_event_results.iloc[-3]['result2'] == female_event_results.iloc[i]['result2']): #accounts for ties for 3rd place
                top3Females = pd.concat([top3Females, female_event_results.iloc[[i]]], ignore_index=True)
                i-=1
                        
            female_event_results = female_event_results.drop(female_event_results.index[-len(top3Females):]) #clears female_event_results of qualifiers
            fieldNonQualifiers = pd.concat([fieldNonQualifiers, female_event_results], ignore_index=True)
            
        if (event in track_events and len(female_event_results) != 0):
            top3Females = female_event_results.head(3)
                
            i = 3
            while (female_event_results.iloc[2]['result2'] == female_event_results.iloc[i]['result2']): #accounts for ties for 3rd place
                top3Females = pd.concat([top3Females, female_event_results.iloc[[i]]], ignore_index=True)
                i+=1
                
            female_event_results = female_event_results.drop(female_event_results.index[:len(top3Females)]) #clears female_event_results of qualifiers
            trackNonQualifiers = pd.concat([trackNonQualifiers, female_event_results], ignore_index=True)
            
        regionalQualifiers = pd.concat([regionalQualifiers, top3Females], ignore_index=True)
        
        if (event in relay_events and len(male_relay_event_results) != 0):
            top3MaleRelays = male_relay_event_results.head(3)
            
            i = 3
            while (male_relay_event_results.iloc[2]['result2'] == male_relay_event_results.iloc[i]['result2']): #accounts for ties for 3rd place
                top3RelayMales = pd.concat([top3RelayMales, male_relay_event_results.iloc[[i]]], ignore_index=True)
                i+=1
                
            male_relay_event_results = male_relay_event_results.drop(male_relay_event_results.index[:len(top3RelayMales)]) #clears female_event_results of qualifiers
            relayNonQualifiers = pd.concat([relayNonQualifiers, male_relay_event_results], ignore_index=True)
            
        if (event in relay_events and len(female_relay_event_results) != 0):
            top3FemaleRelays = female_relay_event_results.head(3)
            
            i = 3
            while (female_relay_event_results.iloc[2]['result2'] == female_relay_event_results.iloc[i]['result2']): #accounts for ties for 3rd place
                top3RelayFemales = pd.concat([top3RelayFemales, female_relay_event_results.iloc[[i]]], ignore_index=True)
                i+=1
                
            female_relay_event_results = female_relay_event_results.drop(female_relay_event_results.index[:len(top3RelayFemales)]) #clears female_event_results of qualifiers
            relayNonQualifiers = pd.concat([relayNonQualifiers, female_relay_event_results], ignore_index=True)
            
fieldNonQualifiers = fieldNonQualifiers.sort_values(by=['result2'], ascending=True) #sorts nonqualifiers by performance
trackNonQualifiers = trackNonQualifiers.sort_values(by=['result2'], ascending=True)
relayNonQualifiers = relayNonQualifiers.sort_values(by=['result2'], ascending=True)
            
maleFieldNonQualifiers = fieldNonQualifiers[fieldNonQualifiers['gender'] == 'Boys'] #splits nonquals into Boys/Girls
femaleFieldNonQualifiers = fieldNonQualifiers[fieldNonQualifiers['gender'] == 'Girls']

top3MaleFieldNonQual = maleFieldNonQualifiers.tail(3)
top3FemaleFieldNonQual = femaleFieldNonQualifiers.tail(3)

i = -4
while (maleFieldNonQualifiers.iloc[-3]['result2'] == maleFieldNonQualifiers.iloc[i]['result2']): #accounts for ties for 3rd place
    top3MaleFieldNonQual = pd.concat([top3MaleFieldNonQual, maleFieldNonQualifiers.iloc[[i]]], ignore_index=True)
    i-=1

i = -4
while (femaleFieldNonQualifiers.iloc[-3]['result2'] == femaleFieldNonQualifiers.iloc[i]['result2']): #accounts for ties for 3rd place
    top3FemaleFieldNonQual = pd.concat([top3FemaleFieldNonQual, femaleFieldNonQualifiers.iloc[[i]]], ignore_index=True)
    i-=1


maleTrackNonQualifiers = trackNonQualifiers[trackNonQualifiers['gender'] == 'Boys']
femaleTrackNonQualifiers = trackNonQualifiers[trackNonQualifiers['gender'] == 'Girls']

top3MaleTrackNonQual = maleTrackNonQualifiers.head(3)
top3FemaleTrackNonQual = femaleTrackNonQualifiers.head(3)

i = 3
while (maleTrackNonQualifiers.iloc[2]['result2'] == maleTrackNonQualifiers.iloc[i]['result2']): #accounts for ties for 3rd place
    top3MaleTrackNonQual.append(maleTrackNonQualifiers.iloc[i])
    i+=1

i = 3
while (femaleTrackNonQualifiers.iloc[2]['result2'] == femaleTrackNonQualifiers.iloc[i]['result2']): #accounts for ties for 3rd place
    top3FemaleTrackNonQual.append(femaleTrackNonQualifiers.iloc[i])
    top3FemaleTrackNonQual = pd.concat([top3FemaleTrackNonQual, femaleTrackNonQualifiers.iloc[[i]]], ignore_index=True)
    i+=1

maleRelayNonQualifiers = relayNonQualifiers[relayNonQualifiers['gender'] == 'Boys']
femaleRelayNonQualifiers = relayNonQualifiers[relayNonQualifiers['gender'] == 'Girls']

top3MaleRelayNonQual = maleRelayNonQualifiers.head(3)
top3FemaleRelayNonQual = femaleRelayNonQualifiers.head(3)

i = 3
while (maleRelayNonQualifiers.iloc[2]['result2'] == maleRelayNonQualifiers.iloc[i]['result2']): #accounts for ties for 3rd place
    top3MaleRelayNonQual.append(maleRelayNonQualifiers.iloc[i])
    i+=1

i = 3
while (femaleRelayNonQualifiers.iloc[2]['result2'] == femaleRelayNonQualifiers.iloc[i]['result2']): #accounts for ties for 3rd place
    top3FemaleRelayNonQual.append(femaleRelayNonQualifiers.iloc[i])
    top3FemaleRelayNonQual = pd.concat([top3FemaleRelayNonQual, femaleRelayNonQualifiers.iloc[[i]]], ignore_index=True)
    i+=1


regionalQualifiers = pd.concat([regionalQualifiers, top3MaleFieldNonQual, top3FemaleFieldNonQual, top3MaleTrackNonQual, top3FemaleTrackNonQual, top3MaleRelayNonQual, top3FemaleRelayNonQual])

/var/folders/jy/f9gpjn257sb09_jfkrnn8yzr0000gn/T/ipykernel_500/3109825142.py:15: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  region_results = regional_results[(regional_results['meet_num'] == meetNumber) & (regional_results['year'] == year) & (all_results['result_type'] == 'Final')] #specifies regional meet and the year, gets FINAL results only
/var/folders/jy/f9gpjn257sb09_jfkrnn8yzr0000gn/T/ipykernel_500/3109825142.py:15: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  region_results = regional_results[(regional_results['meet_num'] == meetNumber) & (regional_results['year'] == year) & (all_results['result_type'] == 'Final')] #specifies regional meet and the year, gets FINAL results only
/var/folders/jy/f9gpjn257sb09_jfkrnn8yzr0000gn/T/ipykernel_500/3109825142.py:15: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  region_results = regional_results[(regional_results['meet_num'] == meetNumber) & (regional_results['year'] == year) & (all_results['result_type'] == 'Final')] #specifies regional meet and the year, gets FINAL results only
/var/folders/jy/f9gpjn257sb09_jfkrnn8yzr0000gn/T/ipykernel_500/3109825142.py:15: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  region_results = regional_results[(regional_results['meet_num'] == meetNumber) & (regional_results['year'] == year) & (all_results['result_type'] == 'Final')] #specifies regional meet and the year, gets FINAL results only
/var/folders/jy/f9gpjn257sb09_jfkrnn8yzr0000gn/T/ipykernel_500/3109825142.py:15: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  region_results = regional_results[(regional_results['meet_num'] == meetNumber) & (regional_results['year'] == year) & (all_results['result_type'] == 'Final')] #specifies regional meet and the year, gets FINAL results only
/var/folders/jy/f9gpjn257sb09_jfkrnn8yzr0000gn/T/ipykernel_500/3109825142.py:15: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  region_results = regional_results[(regional_results['meet_num'] == meetNumber) & (regional_results['year'] == year) & (all_results['result_type'] == 'Final')] #specifies regional meet and the year, gets FINAL results only
/var/folders/jy/f9gpjn257sb09_jfkrnn8yzr0000gn/T/ipykernel_500/3109825142.py:15: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  region_results = regional_results[(regional_results['meet_num'] == meetNumber) & (regional_results['year'] == year) & (all_results['result_type'] == 'Final')] #specifies regional meet and the year, gets FINAL results only
/var/folders/jy/f9gpjn257sb09_jfkrnn8yzr0000gn/T/ipykernel_500/3109825142.py:15: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  region_results = regional_results[(regional_results['meet_num'] == meetNumber) & (regional_results['year'] == year) & (all_results['result_type'] == 'Final')] #specifies regional meet and the year, gets FINAL results only

In [15]:
print(len(regionalQualifiers)) #1242 qualifiers across 2023-2024; 622 for 2023 & 620 for 2024

622

In [17]:
pd.set_option('display.max_rows', None)  # Show all rows
pd.set_option('display.max_columns', None)  # Show all columns
pd.set_option('display.width', None)  # Allow automatic width adjustment
pd.set_option('display.max_colwidth', None)

print(len(regionalQualifiers[regionalQualifiers['event']=='High Jump']))
display(regionalQualifiers[regionalQualifiers['event']=='High Jump'])

60

,athlete_id,first,last,gender,event,result_type,grade,result,result2,place,school_name,enrollment,school_type,nickname,host,meet_type,meet_num,year,school_id,athlete_names,team_name
68,44743.0,LUKE,ROBERTSON,Boys,High Jump,Final,JR,"6' 2""",74.00,3.0,Crown Point,2949.0,Public,Bulldogs,Valparaiso HS,Regional,1,2023,72,NaN,NaN
69,48986.0,MIKE,DROHOSKY,Boys,High Jump,Final,SR,"6' 3""",75.00,2.0,Crown Point,2949.0,Public,Bulldogs,Valparaiso HS,Regional,1,2023,72,NaN,NaN
70,48996.0,JAVION,BALLIN,Boys,High Jump,Final,SR,"6' 4""",76.00,1.0,Westville,295.0,Public,Blackhawks,Valparaiso HS,Regional,1,2023,400,NaN,NaN
71,41738.0,JACOB,SANDLIN,Boys,High Jump,Final,SR,"6' 2""",74.00,4.0,Kankakee Valley,1091.0,Public,Kougars,Valparaiso HS,Regional,1,2023,187,NaN,NaN
72,48999.0,SHAUN,FINLEY,Boys,High Jump,Final,SR,"6' 2""",74.00,5.0,Portage,2271.0,Public,Indians,Valparaiso HS,Regional,1,2023,292,NaN,NaN
73,50770.0,MCKENZI,HOLLAMAN,Girls,High Jump,Final,SR,"5' 3""",63.00,3.0,Merrillville,2095.0,Public,Pirates,Portage,Regional,1,2023,226,NaN,NaN
74,50782.0,SAYLOR,GAPINSKI,Girls,High Jump,Final,FR,"5' 4""",64.00,2.0,Valparaiso,2098.0,Public,Vikings,Portage,Regional,1,2023,377,NaN,NaN
75,50764.0,PRECIOUS,KNIGHT,Girls,High Jump,Final,SR,"5' 5""",65.00,1.0,Hammond Bishop Noll,562.0,Private,Warriors,Portage,Regional,1,2023,148,NaN,NaN
76,50775.0,DAEGES,MORGAN,Girls,High Jump,Final,SR,"5' 3""",63.00,3.0,Hobart,1294.0,Public,Brickies,Portage,Regional,1,2023,161,NaN,NaN
77,50783.0,HAILEY,GEISER,Girls,High Jump,Final,SO,"5' 3""",63.00,5.0,Chesterton,2060.0,Public,Trojans,Portage,Regional,1,2023,51,NaN,NaN
78,50772.0,ENIOLA,OLADEINDE,Girls,High Jump,Final,JR,"5' 3""",63.00,6.0,Lake Central,3098.0,Public,Indians,Portage,Regional,1,2023,195,NaN,NaN
148,49020.0,IAN,JOYCE,Boys,High Jump,Final,SR,"6' 4""",76.00,3.0,South Bend Saint Joseph,811.0,Private,Blue and White,Warsaw HS,Regional,2,2023,330,NaN,NaN
149,49028.0,KOLBY,HAECKER,Boys,High Jump,Final,SR,"6' 8""",80.00,2.0,Manchester,472.0,Public,Squires,Warsaw HS,Regional,2,2023,220,NaN,NaN
150,49037.0,JORDAN,RANDALL,Boys,High Jump,Final,FR,"6' 9""",81.00,1.0,Warsaw Community,2155.0,Public,Tigers,Warsaw HS,Regional,2,2023,385,NaN,NaN
151,50831.0,AYLA,JACKSON,Girls,High Jump,Final,FR,"5' 2""",62.00,2.0,Northwestern,596.0,Public,Tigers,Goshen,Regional,2,2023,271,NaN,NaN
152,43292.0,KAYLA,DOUGLAS,Girls,High Jump,Final,SR,"5' 2""",62.00,3.0,South Bend Adams,1969.0,Public,Eagles,Goshen,Regional,2,2023,327,NaN,NaN
153,48792.0,LENA,SPILLER,Girls,High Jump,Final,SR,"5' 3""",63.00,1.0,Culver Academies,838.0,Private,Eagles,Goshen,Regional,2,2023,73,NaN,NaN
224,44910.0,CADEN,COLLINS,Boys,High Jump,Final,JR,"6' 4""",76.00,4.0,Danville Community,806.0,Public,Warriors,Lafayette Jefferson,Regional,3,2023,76,NaN,NaN
225,49080.0,KADEN,LARK,Boys,High Jump,Final,SO,"6' 6""",78.00,2.0,Lebanon,1042.0,Public,Tigers,Lafayette Jefferson,Regional,3,2023,207,NaN,NaN
226,49095.0,BODE,GILKERSON,Boys,High Jump,Final,SR,"7' 0""",84.00,1.0,Plainfield,1795.0,Public,Quakers,Lafayette Jefferson,Regional,3,2023,290,NaN,NaN
227,49081.0,ROWAN,HALL,Boys,High Jump,Final,SR,"6' 4""",76.00,3.0,Hamilton Southeastern,3433.0,Public,Royals,Lafayette Jefferson,Regional,3,2023,146,NaN,NaN
228,50866.0,WAVERLY,WOOLEVER,Girls,High Jump,Final,FR,"5' 5""",65.00,3.0,Hamilton Heights,729.0,Public,Huskies,Lafayette Jefferson,Regional,3,2023,145,NaN,NaN
229,50870.0,RYLEE,HASSAN,Girls,High Jump,Final,SR,"5' 5""",65.00,2.0,Noblesville,3253.0,Public,Millers,Lafayette Jefferson,Regional,3,2023,251,NaN,NaN
230,50865.0,MALINA,MILLER,Girls,High Jump,Final,SR,"5' 10""",70.00,1.0,Noblesville,3253.0,Public,Millers,Lafayette Jefferson,Regional,3,2023,251,NaN,NaN
297,49133.0,ETHAN,WIDENHOEFER,Boys,High Jump,Final,JR,"6' 5""",77.00,3.0,Homestead,2483.0,Public,Spartans,Carroll (Fort Wayne),Regional,4,2023,162,NaN,NaN
298,49145.0,DONAVIN,BETTS,Boys,High Jump,Final,SR,"6' 5""",77.00,4.0,Marion,1047.0,Public,Giants,Carroll (Fort Wayne),Regional,4,2023,221,NaN,NaN
299,49110.0,ALEX,MEYER,Boys,High Jump,Final,SR,"6' 6""",78.00,1.0,Angola,802.0,Public,Hornets,Carroll (Fort Wayne),Regional,4,2023,7,NaN,NaN
300,49143.0,WINSTON,FRAUHIGER,Boys,High Jump,Final,SR,"6' 5""",77.00,2.0,Norwell,810.0,Public,Knights,Carroll (Fort Wayne),Regional,4,2023,273,NaN,NaN
301,50908.0,ISABELLA,SLONE,Girls,High Jump,Final,FR,"5' 5""",65.00,3.0,Carroll (Fort Wayne),2555.0,Public,Chargers,Carroll (Fort Wayne),Regional,4,2023,42,NaN,NaN
302,50918.0,ELLIE,IRWIN,Girls,High Jump,Final,JR,"5' 6""",66.00,2.0,Homestead,2483.0,Public,Spartans,Carroll (Fort Wayne),Regional,4,2023,162,NaN,NaN
303,50907.0,BAILEY,SINISH,Girls,High Jump,Final,FR,"5' 7""",67.00,1.0,Carroll (Fort Wayne),2555.0,Public,Chargers,Carroll (Fort Wayne),Regional,4,2023,42,NaN,NaN
304,50895.0,MORGAN,GAERTE,Girls,High Jump,Final,JR,"5' 5""",65.00,4.0,Angola,802.0,Public,Hornets,Carroll (Fort Wayne),Regional,4,2023,7,NaN,NaN
375,49174.0,JAIDEN,DRESSELHAUS,Boys,High Jump,Final,SR,"6' 5""",77.00,3.0,Lawrence Central,2365.0,Public,Bears,Lawrence Central,Regional,5,2023,204,NaN,NaN
376,49155.0,EASTON,FOSTER,Boys,High Jump,Final,SO,"6' 5""",77.00,2.0,Monroe Central,293.0,Public,Golden Bears,Lawrence Central,Regional,5,2023,233,NaN,NaN
377,49173.0,LEE,MARTIN,Boys,High Jump,Final,SR,"6' 6""",78.00,1.0,North Central (Indianapolis),3877.0,Public,Panthers,Lawrence Central,Regional,5,2023,253,NaN,NaN
378,43493.0,VICTORIA,HARDNETT,Girls,High Jump,Final,SR,"5' 4""",64.00,3.0,Muncie Central,1451.0,Public,Bearcats,Pike,Regional,5,2023,243,NaN,NaN
379,50946.0,ELLIE,MEYER,Girls,High Jump,Final,SO,"5' 5""",65.00,2.0,Eastern Hancock,384.0,Public,Royals,Pike,Regional,5,2023,90,NaN,NaN
380,44098.0,KYA,CROOKE,Girls,High Jump,Final,SO,"5' 8""",68.00,1.0,Heritage Christian,500.0,Private,Eagles,Pike,Regional,5,2023,157,NaN,NaN
381,43507.0,ELLA,GARVIN,Girls,High Jump,Final,SR,"5' 4""",64.00,4.0,New Castle,866.0,Public,Trojans,Pike,Regional,5,2023,246,NaN,NaN
382,50940.0,ARIEL,NEWMAN,Girls,High Jump,Final,SR,"5' 4""",64.00,5.0,Muncie Central,1451.0,Public,Bearcats,Pike,Regional,5,2023,243,NaN,NaN
449,49204.0,PEYTON,COFFEY,Boys,High Jump,Final,JR,"6' 5""",77.00,3.0,Center Grove,2883.0,Public,Trojans,Greenfield,Regional,6,2023,46,NaN,NaN
450,49194.0,LONTE,WARD,Boys,High Jump,Final,SO,"6' 6""",78.00,2.0,Indianapolis Lutheran,247.0,Private,Saints,Greenfield,Regional,6,2023,175,NaN,NaN
451,49193.0,ELLIOT,RYBA,Boys,High Jump,Final,JR,"6' 7""",79.00,1.0,Greenfield-Central,1444.0,Public,Cougars,Greenfield,Regional,6,2023,137,NaN,NaN
452,50971.0,LYDIA,STAHLEY,Girls,High Jump,Final,FR,"5' 3""",63.00,3.0,Roncalli,1071.0,Private,Royals,Franklin Community,Regional,6,2023,308,NaN,NaN
453,50982.0,MORGAN,SANDROCK,Girls,High Jump,Final,SR,"5' 3""",63.00,2.0,Franklin Community,1668.0,Public,Grizzly Cubs,Franklin Community,Regional,6,2023,125,NaN,NaN
454,43565.0,BROOKE,COFFMAN,Girls,High Jump,Final,SR,"5' 4""",64.00,1.0,Franklin Community,1668.0,Public,Grizzly Cubs,Franklin Community,Regional,6,2023,125,NaN,NaN
455,50981.0,EMERSON,VLCAN,Girls,High Jump,Final,SO,"5' 3""",63.00,4.0,Center Grove,2883.0,Public,Trojans,Franklin Community,Regional,6,2023,46,NaN,NaN
522,42123.0,ANDREW,ADAMS,Boys,High Jump,Final,SR,"6' 3""",75.00,3.0,Eastern (Pekin),416.0,Public,Musketeers,Bloomington North,Regional,7,2023,88,NaN,NaN
523,45182.0,PATRICK,ALSTON,Boys,High Jump,Final,JR,"6' 3""",75.00,2.0,Orleans,276.0,Public,Bulldogs,Bloomington North,Regional,7,2023,277,NaN,NaN
524,49264.0,BRAYDON,PATTERSON,Boys,High Jump,Final,SO,"6' 4""",76.00,1.0,Bedford North Lawrence,1326.0,Public,Stars,Bloomington North,Regional,7,2023,14,NaN,NaN
525,43615.0,LILLY,MERK,Girls,High Jump,Final,None,"5' 3""",63.00,3.0,Terre Haute South Vigo,1717.0,Public,Braves,Bloomington North,Regional,7,2023,358,NaN,NaN
526,51018.0,CALLIE,ALSTON,Girls,High Jump,Final,None,"5' 5""",65.00,2.0,Orleans,276.0,Public,Bulldogs,Bloomington North,Regional,7,2023,277,NaN,NaN
527,43612.0,KARSYN,BUCK,Girls,High Jump,Final,None,"5' 5""",65.00,1.0,Northview,1953.0,Public,Knights,Bloomington North,Regional,7,2023,270,NaN,NaN
597,49305.0,ETHAN,SPINDLER,Boys,High Jump,Final,SR,"6' 5""",77.00,3.0,Gibson Southern,728.0,Public,Titans,Evansville Central,Regional,8,2023,133,NaN,NaN
598,49314.0,JORDAN,BARKSDALE,Boys,High Jump,Final,SR,"6' 7.25""",79.25,2.0,Evansville North,1712.0,Public,Huskies,Evansville Central,Regional,8,2023,105,NaN,NaN
599,49285.0,KADEN,STEWART,Boys,High Jump,Final,SR,"6' 8""",80.00,1.0,Floyd Central,1892.0,Public,Highlanders,Evansville Central,Regional,8,2023,110,NaN,NaN
600,49315.0,DONOVAN,MOORE,Boys,High Jump,Final,FR,"6' 5""",77.00,4.0,Evansville F.J. Reitz,1303.0,Public,Panthers,Evansville Central,Regional,8,2023,102,NaN,NaN
601,44687.0,AVA,ENGLERT,Girls,High Jump,Final,JR,"5' 3""",63.00,3.0,Jasper,1047.0,Public,Wildcats,Evansville Central,Regional,8,2023,182,NaN,NaN
602,47998.0,RILEY,RARICK,Girls,High Jump,Final,FR,"5' 5""",65.00,2.0,Borden,202.0,Public,Braves,Evansville Central,Regional,8,2023,29,NaN,NaN
603,51034.0,JOSIE,PAGE,Girls,High Jump,Final,JR,"5' 8""",68.00,1.0,Wood Memorial,212.0,Public,Trojans,Evansville Central,Regional,8,2023,408,NaN,NaN