In [73]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
from db_util import Database
import pip
#To anyone reading this, I'm sorry

In [5]:
db = Database("/Users/chriswarner/TFData.db")

In [75]:
athlete_df = db.get_all_athlete_results()
meet_df = db.get_all_meets()

In [76]:
meet_df = meet_df[(meet_df["year"] == "2024") & (meet_df["meet_type"] == "Sectional")]

In [77]:
sectional_df = athlete_df[(athlete_df['meet_type'] == "Sectional") & (athlete_df['result_type'] == "Final") & (athlete_df['year'] == 2024)]

In [81]:
podium_df = sectional_df[sectional_df["place"] <= 3]
podium_df2 = sectional_df[sectional_df["place"] <= 3]

In [128]:
other_df = sectional_df[(sectional_df["place"] > 3)]
other_df

,athlete_id,first,last,gender,event,result_type,grade,result,result2,place,school_name,enrollment,school_type,nickname,host,meet_type,meet_num,year,school_id
24571,42210,KALEB,SCHULTZ,Boys,100 Meters,Final,SO,11.49,11.49,4.0,Gary West Side,1127,Public,Cougars,Highland,Sectional,1,2024,131
24572,52531,PEYTON,MUELLER,Boys,100 Meters,Final,SR,11.58,11.58,5.0,Munster,1518,Public,Mustangs,Highland,Sectional,1,2024,244
24573,52534,KING,WHISENTON,Boys,100 Meters,Final,SO,11.63,11.63,6.0,Bowman Leadership Academy,272,Charter,Eagles,Highland,Sectional,1,2024,30
24574,52533,RYAN,BOUKTACHE,Boys,100 Meters,Final,JR,11.69,11.69,7.0,Munster,1518,Public,Mustangs,Highland,Sectional,1,2024,244
24579,42891,AHMIR,FIELDER,Boys,100 Meters,Final,JR,11.33,11.33,4.0,Merrillville,2095,Public,Pirates,Crown Point,Sectional,2,2024,226
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
37341,51807,EMMA,GAFNER,Girls,Pole Vault,Final,JR,"6' 0""",72.00,11.0,Vincennes Rivet,95,Private,Patriots,Princeton Community,Sectional,31,2024,380
37342,57873,LEXI,BUSH,Girls,Pole Vault,Final,FR,"6' 0""",72.00,11.0,South Knox,398,Public,Spartans,Princeton Community,Sectional,31,2024,336
37346,52280,OLIVIA,NIEMEIER,Girls,Pole Vault,Final,JR,"8' 0""",96.00,4.0,Evansville Mater Dei,524,Private,Wildcats,Mt. Vernon (Posey County),Sectional,32,2024,104
37347,57874,LINDSEY,LAINE,Girls,Pole Vault,Final,SR,"7' 0""",84.00,5.0,Evansville Central,1097,Public,Bears,Mt. Vernon (Posey County),Sectional,32,2024,99
37348,57875,MADISON,HICKS,Girls,Pole Vault,Final,JR,"7' 0""",84.00,6.0,Castle,1935,Public,Knights,Mt. Vernon (Posey County),Sectional,32,2024,44

In [118]:
fieldList = ["Long Jump","High Jump","Shot Put","Pole Vault","Discus"]

In [156]:
#State Standards 2024: https://www.scribd.com/document/734190032/2024-IHSAA-State-Standards-3-Participant-Standard

podium_df = sectional_df[(sectional_df["place"] <= 3)]
events = db.get_event()
genders = db.get_gender()
count = 0
x = 1
for g in genders["gender"]:
    for e in events["event"]:
        x = 0
        while x < 32:
            filt = other_df[(other_df['event'] == e) & ((other_df['result2'] < 9999) | (other_df['result2'] > 0)) & (other_df["gender"] == g) & ((other_df["meet_num"] >= x) & (other_df["meet_num"] < (x+4)))]
            filt = filt.sort_values(by='result2')
            #print(len(filt))
            if filt.empty:
                #print(str(e) + " " + str(g))
                tehave = 0
            else:
                headsize = 4
                filt2 = filt.head(len(filt)) #I do not know why it needs this, but filt does not work
                filt2.sort_values(by='first')
                filt2 = filt2.sort_values(by='result2')
                if e in fieldList:
                    filt2.sort_values(by='first')
                    filt2 = filt2.sort_values(by='result2', ascending=False)
                index_last = 3
                old = filt2.iloc[3]
                new = filt2.iloc[index_last+1]
                while old.iloc[8] == new.iloc[8]: #Something strange here is adding lots of rows with wierd new column, no old
                    count += 1
                    headsize += 1
                    index_last += 1
                    old = filt2.iloc[index_last]
                    new = filt2.iloc[index_last+1]
                #if x in fieldList:
                    #filt2 = filt2.sort_values(by='result2', ascending=False)
                #else:
                    #filt2 = filt2.sort_values(by='result2')
                podium_df = pd.concat([podium_df, filt2.head(headsize)], ignore_index=True) #New
            x +=4
    #use head iloc instead of filt iloc

In [140]:
podium_df.sort_values(by='first')
podium_df = podium_df.sort_values(by='result2', ascending=False) 
print(len(podium_df[(podium_df["gender"] == "Girls") & (podium_df["event"] == "100 Meters")])) 
podium_df[(podium_df["gender"] == "Girls") & (podium_df["event"] == "100 Meters")]

128

,athlete_id,first,last,gender,event,result_type,grade,result,result2,place,school_name,enrollment,school_type,nickname,host,meet_type,meet_num,year,school_id
860,53697,CASSY,CHURCHWELL,Girls,100 Meters,Final,JR,13.74,13.74,3.0,Barr-Reeve,287,Public,Vikings,Princeton Community,Sectional,31,2024,12
859,53698,AZARYON,WESLEY,Girls,100 Meters,Final,SR,13.72,13.72,2.0,Princeton Community,631,Public,Tigers,Princeton Community,Sectional,31,2024,294
858,53696,SARAH,FRENCH,Girls,100 Meters,Final,SO,13.57,13.57,1.0,South Knox,398,Public,Spartans,Princeton Community,Sectional,31,2024,336
785,43838,EMMA,ZIMPLEMAN,Girls,100 Meters,Final,SO,13.49,13.49,3.0,Culver Academies,832,Private,Eagles,Bremen,Sectional,6,2024,73
2567,53689,ADDISON,COX,Girls,100 Meters,Final,FR,13.45,13.45,5.0,Southridge,560,Public,Raiders,Perry Central,Sectional,30,2024,345
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
822,44098,KYA,CROOKE,Girls,100 Meters,Final,JR,12.11,12.11,1.0,Heritage Christian,510,Private,Eagles,Lawrence Central,Sectional,19,2024,157
828,44142,JILA,VADEN,Girls,100 Meters,Final,SR,12.10,12.10,1.0,Warren Central,3831,Public,Warriors,Warren Central,Sectional,21,2024,384
798,43940,MAYA,TAYLOR,Girls,100 Meters,Final,SR,12.04,12.04,1.0,Fishers,3644,Public,Tigers,Hamilton Southeastern,Sectional,11,2024,109
801,44503,IZZY,NEAL,Girls,100 Meters,Final,JR,12.03,12.03,1.0,Brownsburg,3308,Public,Bulldogs,Zionsville HS,Sectional,12,2024,34
807,53524,NADIA,FORD,Girls,100 Meters,Final,FR,12.00,12.00,1.0,Carroll (Fort Wayne),2588,Public,Chargers,Ft. Wayne Northrop,Sectional,14,2024,42

In [91]:
relay_df = db.get_all_relay_results()

In [93]:
relay_sectional_df = relay_df[(relay_df['meet_type'] == "Sectional") & (relay_df['year'] == 2024)]
other_relay_df = relay_df[(relay_df["place"] > 3)]

In [95]:
podium_df = pd.concat([podium_df, relay_sectional_df[(relay_sectional_df["place"] <= 3)]], ignore_index=True) #New
genders = db.get_gender()
events = db.get_event()
count = 0
for g in genders["gender"]:
    for x in events["event"]:
        filt = other_relay_df[(other_relay_df['event'] == x) & ((other_relay_df['result2'] < 9999) | (other_relay_df['result2'] > 0)) & (other_relay_df["gender"] == g)]
        filt = filt.sort_values(by='result2')
        if filt.empty:
            blank = 1
        else:
            headsize = 3
            filt2 = filt.head(len(filt)) #I do not know why it needs this, but filt does not work
            filt2.sort_values(by='school_name')
            filt2 = filt2.sort_values(by='result2')
            index_last = 2
            old = filt2.iloc[2]
            new = filt2.iloc[index_last+1]
            while old.iloc[8] == new.iloc[8]: #Something strange here is adding lots of rows with wierd new column, no old
                count += 1
                headsize += 1
                index_last += 1
                old = filt2.iloc[index_last]
                new = filt2.iloc[index_last+1]
            podium_df = pd.concat([podium_df, filt2.head(headsize)], ignore_index=True) #New
    #use head iloc instead of filt iloc

In [71]:
podium_df.to_csv("Regional_Qualifiers.csv", index=False)